### ISSUE TITLE
분야별 테스트데이터셋 생성(~4/12)

### ISSUE THREAD

**Issue by sudog1** [davidkim205/translation#38]
### descrption
현재 테스트 데이터셋은 huggingface 및 aihub 데이터기반의 분야별 10 random sample 데이터, 품질 낮음
다양한 분야에서 높은 품질의 테스트 데이터셋을 구축해야 정확하게 번역 모델을 평가할 수 있음

### task
- [x] 분야별 데이터 종류 정리 (~4/8 17:00)
- [x] 라벨링된 데이터셋(aihub)에서 도메인별 데이터 샘플링(~4/9 16:00)
    - [x] techsci - 기술과학
    - [x] techsci2 - 기술과학
    - [x] expertise - 전문분야
    - [x] food - 식품
    - [x] socialsci - 사회과학
    - [x] patent - 특허
    - [x] MT-new-corpus
    - [x] parallel-translation - 뉴스
    - [x] colloquial - 광고
    - [x] speechtype-based-machine-translation - 구어, 채팅
- [x] 번역하는 translation_domain.py 작성(~4/9 20:00)
- [x] 평가하는 evaluate_domain.py 작성(~4/9 20:30)
- [x] 새로운 테스트 데이터 번역(~4/11 18:00)
- [x] 새 결과에 맞게 평가 및 테이블 생성(~4/12 20:00)

#### 번역(bleu and sbleu)
```
python translation_domain.py --input_file data/domain_test.jsonl --model davidkim205/iris-7b
```
#### 평가
- bleu
```
python evaluate_domain.py results_domain_bleu/
```
- sbleu
```
python evaluate_domain.py results_domain_self/
```

### 문제점
- 정치, 경제... 등 분야별로 나눌수도 있고, 해당 텍스트의 타입(뉴스, 문어체, ...)으로 나눌수도 있음
- 발화(대화체, 구어체, 문어체...)형식에 따라 데이터셋이 존재함. 분류의 어려움
- 도메인 세분화(공학 - 전자, 전기, 기계..., 기초과학 - 물리, 화학, 생물...)의 기준 확립의 어려움
- 라벨링되지 않은 새로운 데이터셋의 통합이 어려움

### 새로운 src
en과 ko가 모두 존재하는 데이터셋
라벨링이 되지 않아서 domain별 구축한 데이터셋과 통합이 어려움

- [alpaca](https://huggingface.co/datasets/tatsu-lab/alpaca) 및 [ko-alpaca](https://huggingface.co/datasets/twodigit/ko-alpaca-data) 
- [belebele](https://huggingface.co/datasets/facebook/belebele)
- [X-TruthfulQA](https://huggingface.co/datasets/zhihz0535/X-TruthfulQA_en_zh_ko_it_es)
- [paws-x](https://huggingface.co/datasets/paws-x)

### 데이터셋 분류 도메인
- 예술
- 정치
- 기계
- 수학
- 전자
- 사회
- 법률
- 문화
- 채팅
- 생명과학
- 보건
- 금융
- 스포츠
- 경제
- 의학
- 전기
- 재료
- ICT
- 특허
- 기후
- 식품
- 뉴스
- 화학
- 한국문화
- 세계
- 관광
- 물리학
- 가정통신문
- 교육
- 농업
- 광고
- 구어

없는 분야
- code
- 수식
- 비속어
