### ISSUE TITLE
다양한 형식의 domain 추가(중지)

### ISSUE THREAD

**Issue by sudog1** [davidkim205/translation#42]
## task
- [ ] 영어 듣기평가 지문 추가(대화) - (~4/17 15:00)
- [ ] 영어 독해 지문 추가
- [ ] 동화, 소설 등 domain 추가
- [ ] 더 세련된 domain으로 기존 domain수정

## description
추가할 domain
- 수능영어(모의고사) 기출 듣기평가 지문
- 수능영어(모의고사) 독해지문
- 동화
- 소설
- llm 인스트럭션
- 추론, 사고, 논리

### 영어 듣기 데이터형식
```
{
    "src":"2023-sat",
    "type":"listening",
    "en":[
        {
            "from":"W",
            "value":"Oliver, I’m so excited about the party for the new members of our tennis \nclub this Friday."
        },
        {
            "from":"M",
            "value":"Me, too. Let’s go through the to-do list. I want it to be perfect."
        },
        {
            "from":"W",
            "value":"Agreed. Did you reserve the Mexican restaurant downtown for the party? "
        },
        {
            "from":"M",
            "value":"Yes, I did. The restaurant is spacious, so it’s perfect for a party like ours."
        },
        {
            "from":"W",
            "value":"Plus, the food there is terrific. And you prepared gifts for the new members, \nright?"
        },
        {
            "from":"M",
            "value":"Yeah, they’re in my car. Did you remind the members about the party?"
        },
        {
            "from":"W",
            "value":"I’ve just sent a text message to everyone."
        },
        {
            "from":"M",
            "value":"Great. What about the tennis competition schedule? Have you printed it \nout?"
        },
        {
            "from":"W",
            "value":"Oh, I almost forgot. I’ll do it tonight. Um, is the music ready?"
        },
        {
            "from":"M",
            "value":"Uh-huh. I made a playlist last night."
        },
        {
            "from":"W",
            "value":"That’s great. I think we’re good to go!"
        }
    ]
}
```

**Comment by davidkim205** [comment]
차후에 진행할때 다시 시작할예정
