### ISSUE TITLE
chatgpt 번역 정성평가(~?)

### ISSUE THREAD

**Issue by sudog1** [davidkim205/translation#45]
## description
번역 결과를 chatgpt로 평가

## task
- [x] json 형식
- [x] csv 형식
- [ ] 보조설명 없는 한 단어로 된 답변
- [ ] 답변의 길이를 몇 문장 이내로 제한, 문자의 개수를 몇 개 이내로 제한
- [ ] 경어체, 평어체만 사용
- [ ] 중요한 단어에는 따옴표를 붙여서 응답

# 다양한 응답 포맷 작성
#### 1. 문자열
```text
[Question]에 대해 [Answer]로 답변하시오. [Format]을 철저하게 준수해야 한다.

### Question
세계에서 가장 유명한 햄버거 브랜드는 무엇인가요?

### Format
[Answer]는 한글로 된 문자열이다.
아래 예시를 참고하여 JSON 객체를 출력해라.
"""json
{"input": [Question], "result": [Answer]}
"""
```
```json
{"input": "세계에서 가장 유명한 햄버거 브랜드는 무엇인가요?", "result": "맥도날드"}
```

#### 2. 리스트
```text
[Question]에 대해 [Answer]로 답변하시오. [Format]을 철저하게 준수해야 한다.

### Question
실존하는 위대한 과학자 5명을 말해보세요.

### Format
[Answer]는 리스트 타입이다.
아래 예시를 참고하여 JSON 객체를 출력해라.
"""json
{"input": [Question], "result": [Answer]}
"""
```
```json
{"input": "실존하는 위대한 과학자 5명을 말해보세요.", "result": ["알버트 아인슈타인", "아이작 뉴턴", "마리 퀴리", "찰스 다윈", "갈릴레오 갈릴레이"]}
```

#### CSV 형식
```text
가상의 인물 5명을 생성하시오. 가상의 인물은 4개의 속성을 가지고 있다.
# [속성]:
이름,나이,성별,키

생성된 인물을 [Format]을 철저하게 준수하여 출력하시오.

### Format
다른 출력 없이 컬럼명이 name,age,gender,height인 csv형식의 데이터만 출력하시오.
```
```csv
name,age,gender,height
Alice,30,Female,165
Bob,25,Male,178
Eve,35,Female,160
Max,40,Male,185
Lily,28,Female,170
```

### ; 구분자
```text
나라 이름 5개를 나열하시오. [Format]을 철저하게 준수해라.

[Format]
예시를 참고하여 각 나라를 ";"로 구분하여 출력하시오.
"""예시
한국;미국;일본;중국;영국
"""
```
```
미국;캐나다;호주;독일;프랑스
```

# chatgpt 번역평가
## 프롬프트 1
```
너의 과제는 번역문의 품질을 평가하는 것이다. 과제를 수행하기 위해 너가 따라야 할 몇 가지 규칙이 있다. 입력으로 원문과 번역문이 주어진다.

# 규칙
- 평가 지침에 따라 평가하시오.
- 자연스럽고 인간적인 방식으로 평가하시오.
- 비판적이고 공정한 태도를 취하시오.
- 평가하기 전에 원문과 번역문을 자세하게 끝까지 읽으시오.
- 사전 지식이나 배경 지식을 적극적으로 활용하시오.
- 평가한 내용을 **2문장 이내**로 요약하여 작성 후, 종합 점수를 산출하시오.
- 출력 형식을 매우 철저하게 준수하시오.

# 평가 지침
1. 누락된 부분이 있는지 꼼꼼하게 확인하시오.
2. 정확하게 번역되었는지 평가하시오.
3. 자연스럽고 유창하게 번역되었는지 평가하시오.
4. 특정 분야의 전문용어를 올바르게 번역하였는지 평가하시오.
5. 번역에 적합한 용어가 없는 경우 원문 그대로 보존하였는지 평가하시오.

# 출력 형식
평가: [요약된 2문장 이내의 평가]
점수: [0-10 사이의 숫자]
```

### 프롬프트 2
```
당신이 번역 품질을 검증하는 숙련된 번역가라고 가정하세요. 영어 원문 [Source]가 주어지고, 누군가 이것을 번역하여 [Target]으로 제공하고 있습니다. 지시를 주의깊게 이해하고, 인간적이고 자연스러운 방식으로 수행하세요.

# [Source]
"""
W: Oliver, I’m so excited about the party for the new members of our tennis
club this Friday.
M: Me, too. Let’s go through the to-do list. I want it to be perfect.
W: Agreed. Did you reserve the Mexican restaurant downtown for the party?
M: Yes, I did. The restaurant is spacious, so it’s perfect for a party like ours.
W: Plus, the food there is terrific. And you prepared gifts for the new members,
right?
M: Yeah, they’re in my car. Did you remind the members about the party?
W: I’ve just sent a text message to everyone.
M: Great. What about the tennis competition schedule? Have you printed it
out?
W: Oh, I almost forgot. I’ll do it tonight. Um, is the music ready?
M: Uh-huh. I made a playlist last night.
W: That’s great. I think we’re good to go!
"""

# [Target]
"""
여: Oliver, 이번 주 금요일 우리 테니스 클럽 신입 회원을 위한 파티로 무척 신나.
남: 나도 그래. 할 일 목록을 살펴보자. 완벽하게 되면 좋겠어.
여: 동의해. 파티를 위해 시내에 있는 멕시코 식당을 예약했니?
남: 응, 했어. 식당이 넓어서 우리 같은 파티에 안성맞춤이야.
여: 게다가 거기 음식도 훌륭해. 그리고 신입 회원을 위한 선물도 준비했지, 그렇지?
남: 응, 내 차에 있어. 회원들에게 파티에 대해 다시 한번 알려줬니?
여: 방금 모두에게 문자 메시지를 보냈어.
"""

# 지시
1. [Target]은 틀린 번역일 가능성이 있습니다. 따라서 [Target]을 참고하지 말고, 온전히 당신이 [Source]를 한글로 번역하세요. 당신의 번역 결과는 [Label]입니다.
2. 당신이 번역한 [Label]이 옳은 번역이라고 가정하세요. 이것을 기준으로 [Target]을 평가해야 합니다.
3. [Target]의 번역 품질을 2문장 이내로 평가해 주세요. 이것을 [Eval]이라 하겠습니다. 1점부터 10점 사이에서 점수를 매기세요. 이것은 [Score]입니다. 출력 형식을 철저히 준수하세요.

# 출력 형식
아래 JSON형식에 맞춰 출력하세요.
"""json
{"source": [Source], "label": [Label], "target": [Target], "eval": [Eval], "score": [Score]}
"""
```

## 테스트 조건
- temperature: 0.3
- top_p: 0.7

## 입력 및 결과
정성평가 기준(사람 평가) 나쁜 데이터 3개, 중간 데이터 3개, 좋은 데이터 4개 평가

## 번역 유형별 결론
- [ ] 문장 누락: 제대로 검출하지 못하는 경우가 많음.
- [x] 잘못된 번역: 잘 평가하지만, 때때로 영어와 한국어의 문장 구조, 어순을 고려하지 않고 평가함.
- [x] 자연스럽고 유창한 번역: 잘 평가함.
- [x] 전문용어 번역: 전문용어의 인식 및 평가는 제대로 동작하지만, 종종 제대로 번역되지 않아도 번역되었다고 하는 경우가 있음.
- [ ] 원문 보존: 번역이 되었음에도 원문을 보존했다고 하는 경우가 많음

### 오류 검출 기준
오류 지침을 마련해서 오류를 검출할 때마다 점수를 매겨서 잘못 번역된 정도를 평가
### 결론
부정적인 지시는 잘 수행하지 못하는 것으로 보임.

### gpt 번역 기준
gpt에게 원문을 번역하도록 한 뒤, gpt번역과 번역문을 비교 및 평가하도록 함
### 결론
제대로 지시를 이해하지 못하여 좋지 않은 결과가 발생.

**Comment by davidkim205** [comment]
아래 이슈와 합친후에 삭제해주세요.
https://github.com/users/davidkim205/projects/2/views/4?pane=issue&itemId=60020192

**Comment by davidkim205** [comment]
차후에 진행할때 다시 시작할예정
